version: '3'
services:
  email_service:
    build:
      context: ./.provision/docker/8.1
      dockerfile: Dockerfile
    ports:
      - '80:8000'
    volumes:
      - '.:/var/www/html'
    env_file:
      - .env
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./.provision/docker/initdb.d/schema.sql:/docker-entrypoint-initdb.d/1schema.sql
      - ./.provision/docker/initdb.d/mocks.sql:/docker-entrypoint-initdb.d/2mocks.sql